### ISSUE TITLE
hw.mov

### ISSUE THREAD

**Issue by J-A16** [cisc3620/7-texturing#1]
Professor, I can't open hw.mov, could you please upload an mp4 maybe? @rivlev

**Comment by rivlev** [comment]
I posted it on the website
www.sci.brooklyn.cuny.edu/~levitan/cisc3620/materials/texture.mov
because github seems to be creating some issues

**Comment by J-A16** [comment]
Thank you.

**Comment by J-A16** [comment]
The link that was in the email worked, though I don't see it in this thread

**Comment by rivlev** [comment]
www.sci.brooklyn.cuny.edu/~levitan/cisc3620/materials/texture.mov
