### ISSUE TITLE
Line down the middle

### ISSUE THREAD

**Issue by J-A16** [cisc3620/7-texturing#3]
@rivlev I finished, with simply multiplying the tex coordinates by 2 instead of changing the range, but had I line down the middle, so I changed the range to see if it helped. Same problem. Do you know why I have a line down the middle between the two reflected pictures? It shows up below the bunnies. Do you care about the line?

**Comment by rivlev** [comment]
The submitted video should look the same as the target video; experiment with the parameters until it matches.
